#!/usr/bin/bash
default_directory="/data/data/com.termux/files/home"
if [ $HOME == "$default_directory" ]
then
        read -p "O sistema pedira acesso a memória interna, aperte enter para prosseguir"
        termux-setup-storage
        sleep 2
        echo "Você escolheu sim, instalando dependências..."
        pkg update
        curl -O https://raw.githubusercontent.com/w3irdguy/droidsploit/main/fixed.sh
        bash fixed.sh
else
        echo "Your device is unreacheable"
fi
